### ISSUE TITLE
video/gif example

### ISSUE THREAD

**Issue by enjalot** [nthitz/d3fx#1]
It would be great to see a youtube video or a gif showing this in action. it sounds like a lot of fun!

**Comment by nthitz** [comment]
:+1: just getting to documentation today and tomorrow :)

**Comment by nthitz** [comment]
Added some gifs to the bottom of the README, tried to showcase a few different functions without going over board or spoiling the most fun stuff :)

**Comment by enjalot** [comment]
:+1:
